version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-users-api
    environment:
      POSTGRES_DB: edge_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  users-api:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: users-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/edge_user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
    command: >
      sh -c "exec java $JAVA_OPTS -jar /app.jar"
    volumes:
      - app-logs:/logs

volumes:
  postgres-data:
  app-logs:
